// Ironcourt default content. Everything here is copied into the user's
// editable plan on first run; edits never touch this file.

const EXERCISES = {
  // ---- Chest ----
  incline_bb_press: { name: "Incline barbell press", muscle: "Chest (upper)", video: "SrqOu55lrYU", demo: "lJ2o89kcnxY",
    cues: ["Bench at 30°, shoulder blades pinned back", "Lower to upper chest, elbows ~45°", "Control 2 s down, press up and slightly back"],
    alts: [["incline_db_press", "Bench or barbell taken"], ["incline_smith_press", "Bench or barbell taken"], ["deficit_pushup", "No equipment"]] },
  incline_db_press: { name: "Incline dumbbell press", muscle: "Chest (upper)", video: "8iPEnn-ltC8", demo: "5CECBjd7HLQ",
    cues: ["Bench at 30°", "Deep stretch at the bottom, dumbbells at chest level", "Press up and in, don't clank at the top"],
    alts: [["incline_bb_press", "Dumbbells taken"], ["incline_smith_press", "Dumbbells taken"], ["deficit_pushup", "No equipment"]] },
  incline_smith_press: { name: "Incline Smith press", muscle: "Chest (upper)", video: "b8DqTO6ak0k", demo: "8urE8Z8AMQ4",
    cues: ["Set bench so bar touches upper chest", "Pause briefly at the stretch", "Easy to push close to failure safely"],
    alts: [["incline_db_press", "Smith taken"], ["deficit_pushup", "No equipment"]] },
  machine_chest_press: { name: "Machine chest press", muscle: "Chest", video: "xUm0BiZCWlQ", demo: "NwzUje3z0qY",
    cues: ["Handles at mid-chest height", "Let the handles come back for a full stretch", "Push to near failure; the machine keeps it safe"],
    alts: [["flat_db_press", "Machine taken"], ["bb_bench", "Machine taken"], ["pushup", "No equipment"]] },
  flat_db_press: { name: "Flat dumbbell press", muscle: "Chest", video: "QsYre__-aro", demo: "YQ2s_Y7g5Qk",
    cues: ["Shoulder blades back and down", "Lower until a deep chest stretch", "Elbows ~45°, not flared"],
    alts: [["machine_chest_press", "Dumbbells taken"], ["bb_bench", "Dumbbells taken"], ["pushup", "No equipment"]] },
  bb_bench: { name: "Barbell bench press", muscle: "Chest", video: "hWbUlkb5Ms4", demo: "ejI1Nlsul9k",
    cues: ["Feet planted, slight arch, blades pinned", "Touch lower chest", "Use a spotter or safeties"],
    alts: [["flat_db_press", "Bench taken"], ["machine_chest_press", "Bench taken"], ["pushup", "No equipment"]] },
  pushup: { name: "Push-up", muscle: "Chest", video: "IODxDxX7oi4", demo: "mm6_WcoCVTA",
    cues: ["Body in one straight line", "Chest to the floor", "Too easy? Go to deficit push-ups"],
    alts: [["deficit_pushup", "Want it harder"]] },
  deficit_pushup: { name: "Deficit push-up", muscle: "Chest", video: "gmNlqsE3Onc", demo: "gmNlqsE3Onc",
    cues: ["Hands on two books, plates or chairs", "Sink the chest below hand level", "Feet on a bed edge to hit upper chest"],
    alts: [["pushup", "Too hard"]] },
  seated_cable_fly: { name: "Seated cable fly", muscle: "Chest", video: "CT7vDnPJZ9w", demo: "4mfLHnFL0Uw",
    cues: ["Bench in the middle of a cable station", "Arms slightly bent, big stretch at the back", "Squeeze hands together in front"],
    alts: [["pec_deck", "Cables taken"], ["db_fly", "No cables"], ["deficit_pushup", "No equipment"]] },
  db_fly: { name: "Dumbbell fly", muscle: "Chest", video: "eozdVDA78K0", demo: "JFm8KbhjibM",
    cues: ["Slight elbow bend, fixed", "Lower until a deep stretch", "Stop before the dumbbells touch at the top"],
    alts: [["seated_cable_fly", "Want constant tension"], ["pec_deck", "Dumbbells taken"], ["deficit_pushup", "No equipment"]] },
  pec_deck: { name: "Pec deck fly", muscle: "Chest", video: "H4mVGHaK2f4", demo: "O-OBCfyh9Fw",
    cues: ["Seat so handles are at chest height", "Let arms go back for a full stretch", "Squeeze, don't slam"],
    alts: [["seated_cable_fly", "Machine taken"], ["db_fly", "Machine taken"], ["deficit_pushup", "No equipment"]] },

  // ---- Back ----
  pendlay_row: { name: "Deficit Pendlay row", muscle: "Back (upper, lats)", video: "Weu9HMHdiDA", demo: "EzFkN5ge5_k",
    cues: ["Stand on a plate, torso near flat", "Bar starts on the floor every rep", "Pull to lower chest, back stays flat"],
    alts: [["cs_db_row", "Lower back tired / bar taken"], ["seated_cable_row", "Bar taken"], ["inverted_row", "No equipment"]] },
  cs_db_row: { name: "Chest-supported dumbbell row", muscle: "Back", video: "vmX58YYK3-8", demo: "tZUYS7X50so",
    cues: ["Incline bench ~30°, chest on the pad", "Let shoulders reach forward for the stretch", "Row elbows back toward hips"],
    alts: [["tbar_row", "Dumbbells taken"], ["seated_cable_row", "Bench taken"], ["inverted_row", "No equipment"]] },
  seated_cable_row: { name: "Seated cable row", muscle: "Back", video: "xQNrFHEMhI4", demo: "UCXxvVItLoM",
    cues: ["Slight forward lean to stretch, then sit tall", "Pull to the belly button", "Don't yank with the lower back"],
    alts: [["cs_db_row", "Cable taken"], ["one_arm_db_row", "Cable taken"], ["inverted_row", "No equipment"]] },
  tbar_row: { name: "Chest-supported T-bar row", muscle: "Back", video: "TyLoy3n_a10", demo: "0UBRfiO4zDs",
    cues: ["Chest stays on the pad", "Full stretch at the bottom", "Pull elbows past the torso"],
    alts: [["cs_db_row", "Machine taken"], ["seated_cable_row", "Machine taken"], ["inverted_row", "No equipment"]] },
  one_arm_db_row: { name: "One-arm dumbbell row", muscle: "Back (lats)", video: "roCP6wCXPqo", demo: "DMo3HJoawrU",
    cues: ["Hand and knee on a bench", "Let the dumbbell hang for a stretch", "Pull toward the hip, not the armpit"],
    alts: [["cs_db_row", "Want more stability"], ["inverted_row", "No equipment"]] },
  inverted_row: { name: "Inverted row", muscle: "Back", video: "11F_O_sZ1Z4", demo: "KOaCM1HMwU0",
    cues: ["Under a sturdy table, Smith bar or railing", "Body straight, pull chest to the bar", "Bend knees to make it easier"],
    alts: [["one_arm_db_row", "Have a dumbbell"]] },
  lat_pulldown: { name: "Wide-grip lat pulldown", muscle: "Back (lats)", video: "lueEJGjTuPQ", demo: "YCKPD4BSD2E",
    cues: ["Thighs locked under the pad", "Full stretch at the top", "Pull elbows down to your sides, chest up"],
    alts: [["neutral_pulldown", "Bar attachment taken"], ["pullup", "Machine taken"], ["inverted_row", "No equipment"]] },
  neutral_pulldown: { name: "Neutral-grip pulldown", muscle: "Back (lats)", video: "aoHXhJ2x2BQ", demo: "GRHLNfmr_oI",
    cues: ["Close neutral handle", "Stretch fully at the top", "Drive elbows down to the ribs"],
    alts: [["lat_pulldown", "Handle taken"], ["chinup", "Machine taken"], ["inverted_row", "No equipment"]] },
  one_arm_pulldown: { name: "Half-kneeling one-arm pulldown", muscle: "Back (lats)", video: "iOAcUe8P_cc", demo: "H9pRHdfS5J4",
    cues: ["Kneel side-on to a high cable", "Let the arm stretch up and across", "Pull elbow down to the hip"],
    alts: [["neutral_pulldown", "Cable taken"], ["one_arm_db_row", "No cables"], ["pullup", "No machines"], ["inverted_row", "No equipment"]] },
  pullup: { name: "Pull-up", muscle: "Back (lats)", video: "eGo4IYlbE5g", demo: "iWpoegdfgtc",
    cues: ["Dead hang at the bottom", "Chest to the bar, no kipping", "Use a band or negatives if needed"],
    alts: [["lat_pulldown", "Too hard / want more reps"], ["chinup", "Want more biceps"], ["inverted_row", "No bar"]] },
  chinup: { name: "Chin-up", muscle: "Back + biceps", video: "mRy9m2Q9_1I", demo: "9JC1EwqezGY",
    cues: ["Palms facing you, shoulder width", "Full hang to chin over bar", "Slow on the way down"],
    alts: [["pullup", "Want more lats"], ["inverted_row", "No bar"]] },

  // ---- Shoulders ----
  cable_lateral: { name: "Cable lateral raise", muscle: "Shoulders (side)", video: "BGw_YA3KiHs", demo: "lq7eLC30b9w",
    cues: ["Cable at hand or hip height, behind you", "Raise out to the side to shoulder height", "Slow lowering, keep tension at the bottom"],
    alts: [["db_lateral", "Cable taken"], ["machine_lateral", "Cable taken"], ["db_lateral", "No equipment (use water bottles or a loaded backpack)"]] },
  db_lateral: { name: "Dumbbell lateral raise", muscle: "Shoulders (side)", video: "PzsMitRdI_8", demo: "OuG1smZTsQQ",
    cues: ["Slight forward lean", "Lead with the elbows, raise to shoulder height", "Light weight, strict reps, 12-20"],
    alts: [["cable_lateral", "Want more tension at the bottom"], ["machine_lateral", "Dumbbells taken"]] },
  machine_lateral: { name: "Machine lateral raise", muscle: "Shoulders (side)", video: "NNAs8jx_zJI", demo: "0o07iGKUarI",
    cues: ["Pads on the outside of the elbows", "Raise to shoulder height", "Easy to push close to failure"],
    alts: [["cable_lateral", "Machine taken"], ["db_lateral", "Machine taken"]] },
  db_shoulder_press: { name: "Seated dumbbell shoulder press", muscle: "Shoulders (front)", video: "qEwKCR5JCog", demo: "HzIiNhHhhtA",
    cues: ["Bench nearly upright", "Lower to ear level", "Press up, don't lock out hard"],
    alts: [["machine_shoulder_press", "Dumbbells taken"], ["bb_ohp", "Bench taken"], ["pike_pushup", "No equipment"]] },
  machine_shoulder_press: { name: "Machine shoulder press", muscle: "Shoulders (front)", video: "3R14MnZbcpw", demo: "WvLMauqrnK8",
    cues: ["Handles start around ear level", "Full range, controlled", "Safe to push near failure"],
    alts: [["db_shoulder_press", "Machine taken"], ["pike_pushup", "No equipment"]] },
  bb_ohp: { name: "Standing overhead press", muscle: "Shoulders (front)", video: "2yjwXTZQDDI", demo: "G2qpTG1Eh40",
    cues: ["Glutes and abs tight", "Bar from collarbone straight up", "Head through at the top"],
    alts: [["db_shoulder_press", "Bar taken"], ["pike_pushup", "No equipment"]] },
  pike_pushup: { name: "Pike push-up", muscle: "Shoulders (front)", video: "lIZ_C4VJnmc", demo: "XckEEwa1BPI",
    cues: ["Hips high, body in an upside-down V", "Lower the head between the hands", "Feet on a bed to make it harder"],
    alts: [["db_shoulder_press", "Have dumbbells"]] },
  reverse_pec_deck: { name: "Reverse pec deck", muscle: "Shoulders (rear)", video: "dC7jhEk-29A", demo: "5YK4bgzXDp0",
    cues: ["Chest on the pad, handles at shoulder height", "Sweep arms out wide", "Light, strict, 12-20 reps"],
    alts: [["reverse_cable_fly", "Machine taken"], ["rear_delt_db_fly", "No machines"], ["prone_y_raise", "No equipment"]] },
  reverse_cable_fly: { name: "Reverse cable fly", muscle: "Shoulders (rear)", video: "IloCYmYWayM", demo: "qz1OLup4W_M",
    cues: ["Cables crossed at shoulder height", "Pull out and back in a wide arc", "Don't shrug"],
    alts: [["reverse_pec_deck", "Cables taken"], ["rear_delt_db_fly", "No cables"], ["prone_y_raise", "No equipment"]] },
  rear_delt_db_fly: { name: "Rear-delt dumbbell fly", muscle: "Shoulders (rear)", video: "buuYPLVXsJg", demo: "34gVHrkaiz0",
    cues: ["Chest on an incline bench or hinge over", "Raise out to the sides, pinkies up", "Light weight"],
    alts: [["reverse_pec_deck", "Want a machine"], ["prone_y_raise", "No equipment"]] },
  prone_y_raise: { name: "Prone Y-raise", muscle: "Shoulders (rear) + upper back", video: "juoKsTqy77E", demo: "w1AWGKubE5U",
    cues: ["Lie face down on floor or bench", "Thumbs up, raise arms in a Y", "Hold 1 s at the top"],
    alts: [["rear_delt_db_fly", "Have dumbbells"]] },

  // ---- Arms ----
  bayesian_curl: { name: "Bayesian cable curl", muscle: "Biceps", video: "8PXe7YNOfb4", demo: "oq7yRDzEPPE",
    cues: ["Face away from a low cable, arm behind you", "Big stretch at the bottom", "Curl without moving the elbow forward"],
    alts: [["incline_db_curl", "Cable taken"], ["db_curl", "No cables"], ["chinup", "No equipment"]] },
  incline_db_curl: { name: "Incline dumbbell curl", muscle: "Biceps", video: "soxrZlIl35U", demo: "aTYlqC_JacQ",
    cues: ["Bench at 45-60°, arms hanging behind", "Keep elbows back", "Slow lowering"],
    alts: [["bayesian_curl", "Bench taken"], ["preacher_curl", "Bench taken"], ["chinup", "No equipment"]] },
  db_curl: { name: "Dumbbell curl", muscle: "Biceps", video: "ykJmrZ5v0Oo", demo: "iixND1P2lik",
    cues: ["Elbows pinned to your sides", "Twist pinkies up at the top", "No swinging"],
    alts: [["bayesian_curl", "Want more stretch"], ["hammer_curl", "Wrist sore"]] },
  preacher_curl: { name: "Preacher curl", muscle: "Biceps", video: "Gydpcouclx8", demo: "sxA__DoLsgo",
    cues: ["Armpits snug on the pad", "Lower nearly straight, under control", "Don't bounce out of the bottom"],
    alts: [["incline_db_curl", "Pad taken"], ["db_curl", "Pad taken"]] },
  hammer_curl: { name: "Hammer curl", muscle: "Biceps + forearms", video: "BRVDS6HVR9Q", demo: "XOEL4MgekYE",
    cues: ["Neutral grip, thumbs up", "Elbows still", "Good for squash forearms too"],
    alts: [["db_curl", "Want more biceps"]] },
  oh_cable_tri: { name: "Overhead cable triceps extension", muscle: "Triceps", video: "GzmlxvSFE7A", demo: "kqidUIf1eJE",
    cues: ["Face away from the cable, rope behind the head", "Deep stretch with elbows up", "Extend fully, elbows stay pointed forward"],
    alts: [["oh_db_tri", "Cable taken"], ["skullcrusher", "No cables"], ["diamond_pushup", "No equipment"]] },
  oh_db_tri: { name: "Overhead dumbbell triceps extension", muscle: "Triceps", video: "-Vyt2QdsR7E", demo: "a9oPnZReIRE",
    cues: ["Hold one dumbbell with both hands", "Lower behind the head for a big stretch", "Elbows point up, not out"],
    alts: [["oh_cable_tri", "Want constant tension"], ["bench_dip", "No equipment"]] },
  skullcrusher: { name: "EZ-bar skull crusher", muscle: "Triceps", video: "d_KZxkY_0cM", demo: "l3rHYPtMUo8",
    cues: ["Lower the bar behind the head, not to the nose", "Elbows stay narrow", "Controlled"],
    alts: [["oh_db_tri", "Bar taken"], ["diamond_pushup", "No equipment"]] },
  cable_kickback: { name: "Cable triceps kickback", muscle: "Triceps", video: "ZvF4Oi_6Vtg", demo: "DYsQWSbj7UM",
    cues: ["Hinge forward, upper arm by your side", "Extend until straight behind you", "One arm at a time"],
    alts: [["db_kickback", "Cable taken"], ["pushdown", "Want heavier"], ["bench_dip", "No equipment"]] },
  db_kickback: { name: "Dumbbell kickback", muscle: "Triceps", video: "6SS6K3lAwZ8", demo: "JPmbMOu4IYw",
    cues: ["Upper arm parallel to the floor", "Straighten fully, squeeze", "Light weight"],
    alts: [["cable_kickback", "Have cables"], ["bench_dip", "No equipment"]] },
  pushdown: { name: "Triceps pushdown", muscle: "Triceps", video: "_w-HpW70nSQ", demo: "-xa-6cQaZKY",
    cues: ["Elbows pinned at your sides", "Push down until straight", "Rope or bar both fine"],
    alts: [["oh_cable_tri", "Want more stretch"], ["db_kickback", "No cables"], ["diamond_pushup", "No equipment"]] },
  diamond_pushup: { name: "Diamond push-up", muscle: "Triceps + chest", video: "J0DnG1_S92I", demo: "Lz1aFtuNvEQ",
    cues: ["Hands together under the chest", "Elbows track back", "Drop to knees if needed"],
    alts: [["bench_dip", "Want another option"]] },
  bench_dip: { name: "Bench dip", muscle: "Triceps", video: "c3ZGl4pAwZ4", demo: "larQGD02ndE",
    cues: ["Hands on a bed or chair edge", "Lower until elbows hit 90°", "Stop if shoulders complain"],
    alts: [["diamond_pushup", "Shoulders sore"]] },

  // ---- Quads / legs ----
  hack_squat: { name: "Hack squat", muscle: "Quads", video: "0tn5K9NlCfo", demo: "rYgNArpwE7E",
    cues: ["Feet mid-platform, shoulder width", "Go as deep as you can with a flat back", "Drive up through the whole foot"],
    alts: [["back_squat", "Machine taken"], ["smith_squat", "Machine taken"], ["goblet_squat", "Dumbbells only"], ["bss", "No equipment (bodyweight)"]] },
  back_squat: { name: "Barbell back squat", muscle: "Quads + glutes", video: "gcNh17Ckjgg", demo: "i7J5h7BJ07g",
    cues: ["Bar on upper traps, brace hard", "Sit down between the heels, knees out", "Depth: hip crease below the knee"],
    alts: [["hack_squat", "Rack taken"], ["smith_squat", "Rack taken"], ["goblet_squat", "Dumbbells only"], ["bss", "No equipment (bodyweight)"]] },
  smith_squat: { name: "Smith machine squat", muscle: "Quads", video: "AHnX-aimA4E", demo: "-eO_VydErV0",
    cues: ["Feet slightly in front of the bar", "Deep and controlled", "Safe to push near failure"],
    alts: [["leg_press", "Smith taken"], ["hack_squat", "Smith taken"], ["goblet_squat", "Dumbbells only"], ["bw_squat", "No equipment"]] },
  leg_press: { name: "Leg press", muscle: "Quads + glutes", video: "K5n2vg3oZa4", demo: "yZmx_Ac3880",
    cues: ["Feet shoulder width, mid-platform", "Lower until hips start to curl, no further", "Don't lock the knees at the top"],
    alts: [["hack_squat", "Machine taken"], ["smith_squat", "Machine taken"], ["goblet_squat", "Dumbbells only"], ["bw_squat", "No equipment"]] },
  goblet_squat: { name: "Goblet squat", muscle: "Quads", video: "MeIiIdhvXT4", demo: "nfX7IFK9UNI",
    cues: ["Dumbbell held at the chest", "Elbows inside the knees at the bottom", "Slow 3 s down"],
    alts: [["bss", "Want it harder"], ["bw_squat", "No equipment"]] },
  bw_squat: { name: "Bodyweight squat (slow tempo)", muscle: "Quads", video: "Ul2idJKmpAc", demo: "0EpP3pYUYTk",
    cues: ["3 s down, 1 s pause, up", "High reps, 20-30", "Make it harder with a backpack"],
    alts: [["bss", "Too easy"]] },
  bss: { name: "Bulgarian split squat", muscle: "Quads + glutes", video: "SkNsa3eBwLA", demo: "Fmjj7wFJWRE",
    cues: ["Back foot on a bench, front foot far enough forward", "Drop the back knee straight down", "Torso upright for quads, lean for glutes"],
    alts: [["walking_lunge", "Bench taken"], ["reverse_lunge", "Balance off today"], ["step_up", "Knee unhappy"]] },
  walking_lunge: { name: "Walking lunge", muscle: "Quads + glutes", video: "mAgbXQdd4LM", demo: "eFWCn5iEbTU",
    cues: ["Long steps, back knee nearly touches", "Stay tall", "Dumbbells or bodyweight"],
    alts: [["bss", "Want more stretch"], ["reverse_lunge", "No space to walk"]] },
  reverse_lunge: { name: "Reverse lunge", muscle: "Quads + glutes", video: "sjlsISvHyZs", demo: "TQfhY5oJ_Sc",
    cues: ["Step back, drop the back knee", "Push through the front heel", "Easier on the knees"],
    alts: [["bss", "Want harder"], ["step_up", "Knee unhappy"]] },
  step_up: { name: "Dumbbell step-up", muscle: "Quads + glutes", video: "7AtIjR-QqVA", demo: "PHGUzLhhsbQ",
    cues: ["Box at knee height", "Drive through the top foot only", "Control the way down"],
    alts: [["bss", "Want harder"]] },
  leg_ext: { name: "Leg extension", muscle: "Quads", video: "ljO4jkwv8wQ", demo: "m0FOpMEgero",
    cues: ["Knee lined up with the machine pivot", "Lean back slightly for more stretch", "Squeeze at the top, slow down"],
    alts: [["reverse_nordic", "Machine taken / no equipment"], ["sissy_squat", "No equipment"]] },
  reverse_nordic: { name: "Reverse Nordic", muscle: "Quads", video: "x2K8uH7dcqg", demo: "x2K8uH7dcqg",
    cues: ["Kneel on something soft, body straight", "Lean back slowly from the knees", "Small range at first"],
    alts: [["sissy_squat", "Knees sore when kneeling"]] },
  sissy_squat: { name: "Sissy squat", muscle: "Quads", video: "HIB6TFqLO0Q", demo: "FTmbNjUu7CI",
    cues: ["Hold a door frame for balance", "Knees forward, heels up, lean back", "Go only as deep as feels OK"],
    alts: [["reverse_nordic", "Prefer kneeling"]] },

  // ---- Hamstrings / glutes ----
  rdl: { name: "Romanian deadlift", muscle: "Hamstrings + glutes", video: "_oyxCn2iSjU", demo: "CN_7cz3P-1U",
    cues: ["Soft knees, push hips back", "Bar slides down the thighs", "Stop at a big hamstring stretch, back flat"],
    alts: [["db_rdl", "Bar taken"], ["back_ext", "Lower back tired"], ["sl_rdl", "No equipment"]] },
  db_rdl: { name: "Dumbbell RDL", muscle: "Hamstrings + glutes", video: "hQgFixeXdZo", demo: "cYKYGwcg0U8",
    cues: ["Dumbbells close to the legs", "Hips back, flat back", "Feel the stretch, then stand"],
    alts: [["rdl", "Want heavier"], ["sl_rdl", "No equipment"]] },
  sl_rdl: { name: "Single-leg RDL", muscle: "Hamstrings + glutes", video: "J0bEKhnP-Mw", demo: "JQZqPsmeesc",
    cues: ["Hinge on one leg, other leg goes back", "Hips stay square", "Hold a wall for balance at first"],
    alts: [["db_rdl", "Have dumbbells"]] },
  back_ext: { name: "45° back extension", muscle: "Hamstrings + glutes", video: "OMb1VFQK9Tk", demo: "5_ejbGfdAQE",
    cues: ["Pad just below the hips", "Round down, hinge up with glutes", "Hold a plate to load it"],
    alts: [["rdl", "Bench taken"], ["sl_rdl", "No equipment"]] },
  seated_leg_curl: { name: "Seated leg curl", muscle: "Hamstrings", video: "ELOCsoDSmrg", demo: "Orxowest56U",
    cues: ["Lean forward slightly for a bigger stretch", "Curl all the way under", "Slow on the way up"],
    alts: [["lying_leg_curl", "Machine taken"], ["nordic_curl", "No machines"], ["slider_curl", "No equipment"]] },
  lying_leg_curl: { name: "Lying leg curl", muscle: "Hamstrings", video: "jxctD6fL_FQ", demo: "n5WDXD_mpVY",
    cues: ["Hips pressed into the pad", "Full curl, slow lowering", "No hip lift"],
    alts: [["seated_leg_curl", "Machine taken"], ["slider_curl", "No equipment"]] },
  nordic_curl: { name: "Nordic curl", muscle: "Hamstrings", video: "3-4pKUhkzoQ", demo: "kjv4WQXWl_A",
    cues: ["Feet anchored under something heavy", "Lower as slowly as you can", "Catch yourself with hands, push back up"],
    alts: [["slider_curl", "Too hard"]] },
  slider_curl: { name: "Towel slider leg curl", muscle: "Hamstrings", video: "0z7O5m3kMO0", demo: "HaR-vvFwb7A",
    cues: ["Lie on your back, heels on a towel on a smooth floor", "Hips up, slide heels in and out", "One leg at a time to make it harder"],
    alts: [["nordic_curl", "Too easy"]] },
  hip_thrust: { name: "Barbell hip thrust", muscle: "Glutes", video: "ZHM4n4aDgXg", demo: "EF7jXP17DPE",
    cues: ["Upper back on a bench, bar on hips (use a pad)", "Drive up, chin tucked", "Pause at the top"],
    alts: [["back_ext", "Bar taken"], ["sl_rdl", "No equipment"]] },

  // ---- Calves ----
  standing_calf: { name: "Standing calf raise", muscle: "Calves", video: "SVtg-1loH4c", demo: "N3awlEyTY98",
    cues: ["Pause 2 s at the bottom stretch", "Up onto the big toe", "No bouncing"],
    alts: [["seated_calf", "Machine taken"], ["sl_calf", "No equipment"]] },
  seated_calf: { name: "Seated calf raise", muscle: "Calves", video: "6O5hh1rBtx8", demo: "2Q-HQ3mnePg",
    cues: ["Pad on the lower thigh", "Deep stretch, pause", "Full height at the top"],
    alts: [["standing_calf", "Machine taken"], ["sl_calf", "No equipment"]] },
  sl_calf: { name: "Single-leg calf raise on a step", muscle: "Calves", video: "IphGZ8OlfYg", demo: "_gEx2ijsmNM",
    cues: ["Ball of the foot on a stair edge", "Drop the heel low, pause", "Hold a dumbbell to load it"],
    alts: [["standing_calf", "Have a machine"]] },

  // ---- Core ----
  hanging_leg_raise: { name: "Hanging leg raise", muscle: "Abs", video: "Pr1ieGZ5atk", demo: "7FwGZ8qY5OU",
    cues: ["Dead hang, no swinging", "Curl the pelvis up, not just the legs", "Bend knees to make it easier"],
    alts: [["reverse_crunch", "No bar"], ["lying_leg_raise", "No equipment"]] },
  lying_leg_raise: { name: "Lying leg raise", muscle: "Abs", video: "JB2oyawG9KI", demo: "9fzAZhskpMM",
    cues: ["Lower back pressed to the floor", "Lower legs slowly", "Hands under hips if needed"],
    alts: [["reverse_crunch", "Lower back complains"]] },
  reverse_crunch: { name: "Reverse crunch", muscle: "Abs", video: "hyv14e2QDq0", demo: "XY8KzdDcMFg",
    cues: ["Knees bent, curl hips off the floor", "Slow down", "No momentum"],
    alts: [["lying_leg_raise", "Want harder"]] },
  cable_crunch: { name: "Cable crunch", muscle: "Abs", video: "3qjoXDTuyOE", demo: "6GMKPQVERzw",
    cues: ["Kneel, rope by your head", "Curl ribs toward hips, hips stay still", "Load it heavy, 10-15 reps"],
    alts: [["decline_crunch", "Cable taken"], ["ab_wheel", "No cables"], ["reverse_crunch", "No equipment"]] },
  decline_crunch: { name: "Decline crunch", muscle: "Abs", video: "FRzQXeN1hro", demo: "DAnTf16NcT0",
    cues: ["Feet hooked on a decline bench", "Curl up, don't yank the neck", "Hold a plate to load it"],
    alts: [["cable_crunch", "Want heavier"], ["reverse_crunch", "No equipment"]] },
  ab_wheel: { name: "Ab wheel rollout", muscle: "Abs", video: "rqiTPdK1c_I", demo: "3b8K6BCvBBA",
    cues: ["From the knees, ribs down", "Roll out only as far as you control", "Pull back with the abs"],
    alts: [["plank", "No wheel"]] },
  plank: { name: "Plank", muscle: "Abs", video: "A2b2EmIg0dA", demo: "mwlp75MS6Rg",
    cues: ["Elbows under shoulders", "Squeeze glutes, ribs down", "30-60 s holds"],
    alts: [["ab_wheel", "Too easy"]] },

  // ---- Conditioning ----
  incline_walk: { name: "Incline treadmill walk", muscle: "Cardio (low stress)", video: "NAsObfFJXvE", demo: "9ccVxEvWtpA",
    cues: ["Incline 8-12, speed 4.5-5.5 km/h", "Don't hold the rails", "20 minutes, easy breathing"],
    alts: [] },
};

// Sessions. reps is text so ranges and "per leg" read naturally.
const SESSIONS = {
  // Cut week: no exercise appears twice in the same rotation.
  U1: { name: "Upper 1", focus: "Strength bias", items: [
    { ex: "incline_bb_press", sets: 3, reps: "6-8", rest: 150 },
    { ex: "pendlay_row", sets: 3, reps: "6-10", rest: 150 },
    { ex: "lat_pulldown", sets: 3, reps: "8-12", rest: 120 },
    { ex: "seated_cable_fly", sets: 2, reps: "12-15", rest: 90 },
    { ex: "cable_lateral", sets: 3, reps: "10-15", rest: 75 },
    { ex: "oh_cable_tri", sets: 2, reps: "10-12", rest: 75 },
    { ex: "bayesian_curl", sets: 2, reps: "10-12", rest: 75 } ] },
  L1: { name: "Lower 1", focus: "Squat + hinge", items: [
    { ex: "hack_squat", sets: 3, reps: "6-8", rest: 180 },
    { ex: "rdl", sets: 3, reps: "8-10", rest: 150 },
    { ex: "seated_leg_curl", sets: 3, reps: "10-12", rest: 90 },
    { ex: "leg_ext", sets: 2, reps: "12-15", rest: 90 },
    { ex: "standing_calf", sets: 3, reps: "10-15", rest: 60 },
    { ex: "hanging_leg_raise", sets: 3, reps: "10-15", rest: 60 } ] },
  U2: { name: "Upper 2", focus: "Size bias", items: [
    { ex: "machine_chest_press", sets: 3, reps: "8-12", rest: 120 },
    { ex: "one_arm_pulldown", sets: 3, reps: "10-12", rest: 90 },
    { ex: "tbar_row", sets: 3, reps: "10-12", rest: 120 },
    { ex: "db_shoulder_press", sets: 2, reps: "8-12", rest: 120 },
    { ex: "machine_lateral", sets: 3, reps: "12-15", rest: 75 },
    { ex: "reverse_pec_deck", sets: 2, reps: "12-15", rest: 75 },
    { ex: "incline_db_curl", sets: 2, reps: "10-12", rest: 75 },
    { ex: "cable_kickback", sets: 2, reps: "10-12", rest: 75 } ] },
  L2: { name: "Lower 2", focus: "Single-leg + abs", items: [
    { ex: "bss", sets: 3, reps: "8-10 / leg", rest: 120 },
    { ex: "leg_press", sets: 3, reps: "10-12", rest: 150 },
    { ex: "lying_leg_curl", sets: 3, reps: "10-12", rest: 90 },
    { ex: "seated_calf", sets: 3, reps: "12-15", rest: 60 },
    { ex: "cable_crunch", sets: 3, reps: "10-15", rest: 60 } ] },
  OPT: { name: "Arms + delts", focus: "Optional, skip if legs are tired", items: [
    { ex: "hammer_curl", sets: 3, reps: "10-12", rest: 60 },
    { ex: "pushdown", sets: 3, reps: "10-12", rest: 60 },
    { ex: "reverse_cable_fly", sets: 2, reps: "12-15", rest: 60 },
    { ex: "ab_wheel", sets: 3, reps: "8-12", rest: 60 },
    { ex: "incline_walk", sets: 1, reps: "20 min", rest: 0 } ] },
  HOME: { name: "Hostel room", focus: "No equipment, 35 min", items: [
    { ex: "deficit_pushup", sets: 3, reps: "to 1 short of failure", rest: 90 },
    { ex: "inverted_row", sets: 3, reps: "8-15", rest: 90 },
    { ex: "bss", sets: 3, reps: "12-15 / leg", rest: 90 },
    { ex: "pike_pushup", sets: 3, reps: "6-12", rest: 90 },
    { ex: "sl_rdl", sets: 3, reps: "10-12 / leg", rest: 60 },
    { ex: "slider_curl", sets: 2, reps: "10-15", rest: 60 },
    { ex: "diamond_pushup", sets: 2, reps: "to 1 short of failure", rest: 60 },
    { ex: "plank", sets: 3, reps: "45 s", rest: 45 } ] },
  FBA: { name: "Full body A", focus: "Term mode", items: [
    { ex: "hack_squat", sets: 3, reps: "6-10", rest: 180 },
    { ex: "incline_db_press", sets: 3, reps: "8-10", rest: 120 },
    { ex: "lat_pulldown", sets: 3, reps: "8-12", rest: 120 },
    { ex: "rdl", sets: 2, reps: "8-10", rest: 150 },
    { ex: "cable_lateral", sets: 3, reps: "12-15", rest: 60 },
    { ex: "bayesian_curl", sets: 2, reps: "10-12", rest: 60 },
    { ex: "oh_cable_tri", sets: 2, reps: "10-12", rest: 60 } ] },
  FBB: { name: "Full body B", focus: "Term mode", items: [
    { ex: "bss", sets: 3, reps: "8-10 / leg", rest: 120 },
    { ex: "machine_chest_press", sets: 3, reps: "8-12", rest: 120 },
    { ex: "tbar_row", sets: 3, reps: "10-12", rest: 120 },
    { ex: "seated_leg_curl", sets: 3, reps: "10-12", rest: 90 },
    { ex: "db_shoulder_press", sets: 2, reps: "8-12", rest: 120 },
    { ex: "reverse_pec_deck", sets: 2, reps: "12-15", rest: 60 },
    { ex: "cable_crunch", sets: 3, reps: "10-15", rest: 60 } ] },
  FBC: { name: "Full body C", focus: "Term mode", items: [
    { ex: "smith_squat", sets: 3, reps: "8-12", rest: 150 },
    { ex: "flat_db_press", sets: 3, reps: "8-10", rest: 150 },
    { ex: "one_arm_pulldown", sets: 3, reps: "10-12", rest: 90 },
    { ex: "back_ext", sets: 2, reps: "10-15", rest: 90 },
    { ex: "machine_lateral", sets: 3, reps: "12-15", rest: 60 },
    { ex: "incline_db_curl", sets: 2, reps: "10-12", rest: 60 },
    { ex: "cable_kickback", sets: 2, reps: "10-12", rest: 60 } ] },
};

// Meal slots. Each slot has interchangeable options; the first is the default.
const MEALS = [
  { id: "breakfast", time: "10:00", name: "Breakfast", options: [
    { name: "Egg bhurji", detail: "2 whole eggs + 3 whites, onion, tomato. 1 roti or 2 multigrain toast. 1 fruit", kcal: 450, protein: 30 },
    { name: "Oats + whey", detail: "60 g oats in 250 ml milk, 1 scoop whey stirred in, 1 banana", kcal: 520, protein: 40 },
    { name: "Omelette + toast", detail: "3-egg omelette (2 yolks), veggies, 2 toast, black coffee", kcal: 420, protein: 26 } ] },
  { id: "postgym", time: "13:00", name: "Post-gym shake", options: [
    { name: "Whey in water", detail: "1 scoop", kcal: 120, protein: 24 },
    { name: "Whey in milk", detail: "1 scoop + 250 ml toned milk", kcal: 270, protein: 32 } ] },
  { id: "lunch", time: "14:00", name: "Lunch", veg: true, cook: true, options: [
    { name: "Soya chunk curry", detail: "50 g dry soya chunks, 1 katori dal, 2 roti, sabzi, 1 katori curd", kcal: 700, protein: 46 },
    { name: "Paneer tikka / bhurji", detail: "100 g paneer, 1 katori dal, 2 roti, salad, curd. Max 2-3 times a week (saturated fat)", kcal: 790, protein: 40 },
    { name: "Tofu bhurji", detail: "150 g firm tofu, 2 roti, 1 katori dal, salad", kcal: 600, protein: 38 },
    { name: "Rajma / chole + curd", detail: "1.5 katori rajma or chole, 1 roti or ½ cup rice, curd, salad. Lower protein: add a whey shake later", kcal: 600, protein: 25 } ] },
  { id: "snack", time: "17:00", name: "Pre-squash snack", options: [
    { name: "Banana + hung curd", detail: "1 banana, 150 g hung curd or Greek yogurt", kcal: 250, protein: 14 },
    { name: "Roasted chana + fruit", detail: "40 g roasted chana, 1 apple or banana", kcal: 250, protein: 9 },
    { name: "Sprouts chaat", detail: "1 big katori sprouts, onion, tomato, lemon", kcal: 200, protein: 12 } ] },
  { id: "dinner", time: "21:00", name: "Dinner", cook: true, options: [
    { name: "Chicken tikka / tandoori", detail: "200 g raw chicken breast, big salad or sabzi, 1 roti", kcal: 550, protein: 50 },
    { name: "Prawn masala (dry)", detail: "200 g prawns, 1 tsp oil, sabzi, ½ cup rice", kcal: 520, protein: 44 },
    { name: "Chicken stir-fry", detail: "200 g chicken, lots of veg, 1 tsp oil, 1 roti", kcal: 500, protein: 48 },
    { name: "Egg curry", detail: "4 eggs (2 yolks), light gravy, sabzi, 1 roti", kcal: 450, protein: 30 } ] },
  { id: "nuts", time: "21:30", name: "Nuts", options: [
    { name: "Almonds / peanuts", detail: "15-20 g", kcal: 120, protein: 4 } ] },
];

// Quick-add foods, approximate per serving. Indian home, mess and restaurant staples.
const FOODS = [
  ["Roti (medium)", 100, 3], ["Rice, 1 cup cooked", 200, 4], ["Dal, 1 katori", 120, 7],
  ["Rajma / chole, 1 katori", 150, 8], ["Sabzi, 1 katori", 100, 3], ["Curd, 1 katori", 90, 5],
  ["Hung curd / Greek yogurt, 150 g", 150, 15], ["Paneer, 100 g", 265, 18], ["Tofu, 100 g", 130, 14],
  ["Soya chunks, 50 g dry", 170, 26], ["Egg, whole", 72, 6], ["Egg white", 17, 4],
  ["Chicken breast, 100 g raw", 120, 23], ["Chicken curry (mess), 1 katori", 250, 20], ["Prawns, 100 g raw", 100, 20],
  ["Whey, 1 scoop", 120, 24], ["Milk, 250 ml toned", 150, 8], ["Banana", 105, 1],
  ["Apple", 95, 0], ["Roasted chana, 40 g", 150, 8], ["Peanuts, 30 g", 170, 7],
  ["Almonds, 20 g", 115, 4], ["Sprouts, 1 katori", 100, 7], ["Poha, 1 plate", 250, 5],
  ["Upma, 1 plate", 250, 6], ["Idli ×2 + sambar", 200, 7], ["Dosa + sambar", 300, 7],
  ["Samosa", 260, 4], ["Chai with sugar", 90, 3], ["Black coffee", 5, 0], ["Chai, no sugar", 45, 3],
  ["Butter chicken, 1 katori", 450, 22], ["Biryani, 1 plate", 700, 25], ["Butter naan", 300, 7],
  ["Pizza, 1 slice", 280, 12], ["Burger", 500, 20], ["Gulab jamun", 150, 2],
  ["Beer, 330 ml", 140, 1], ["Strong beer, 650 ml", 390, 3], ["Whisky / rum, 30 ml", 70, 0],
  ["Vodka / gin, 30 ml", 65, 0], ["Cola, 250 ml", 105, 0], ["Diet cola / soda", 1, 0],
];

const DEFAULT_PLAN = {
  version: 2,
  mode: "cut", // cut | term
  cutStart: "2026-10-09",
  cutEnd: "2026-11-05",
  partyDates: ["2026-10-08", "2026-10-17", "2026-10-18", "2026-10-19", "2026-10-20", "2026-10-21", "2026-10-22"],
  targets: { kcal: 2300, protein: 155, water: 3500, steps: 9000, sleep: 8 },
  schedule: [
    { time: "09:30", title: "Wake up + 500 ml water", kind: "habit" },
    { time: "10:00", title: "Breakfast", kind: "meal", ref: "breakfast" },
    { time: "11:30", title: "Black coffee #1", kind: "habit" },
    { time: "11:45", title: "Gym", kind: "gym" },
    { time: "13:00", title: "Whey shake", kind: "meal", ref: "postgym" },
    { time: "14:00", title: "Veg lunch", kind: "meal", ref: "lunch" },
    { time: "17:00", title: "Pre-squash snack", kind: "meal", ref: "snack" },
    { time: "17:30", title: "Black coffee #2", kind: "habit" },
    { time: "18:30", title: "Squash", kind: "squash" },
    { time: "21:00", title: "Dinner", kind: "meal", ref: "dinner" },
    { time: "21:30", title: "Nuts", kind: "meal", ref: "nuts" },
    { time: "22:30", title: "Kitchen closes", kind: "habit" },
    { time: "01:30", title: "Sleep (8 h)", kind: "habit" },
  ],
  rotations: {
    cut: ["U1", "L1", "REST", "U2", "L2", "OPT", "REST"],
    term: ["FBA", "FBB", "FBC"],
  },
  sessions: SESSIONS,
  exercises: EXERCISES,
  meals: MEALS,
  foods: FOODS,
  partyRules: [
    "Spirits with soda or diet mixer, not beer",
    "Protein dinner before the first drink",
    "A glass of water between drinks",
    "Stop at 3-4 drinks",
    "No late-night ordering",
    "Train in the morning, not the day after",
  ],
  sundayGuide: {
    order: ["Tandoori chicken / chicken tikka", "Grilled fish or prawns", "Dal tadka", "Tandoori roti (not butter naan)", "Salad, raita", "Egg bhurji"],
    avoid: ["Butter chicken, malai tikka, korma", "Biryani", "Butter naan, paratha", "Fried starters, chilli chicken", "Desserts", "Sugary drinks"],
  },
  grocery: [
    "Eggs: 3 dozen",
    "Chicken breast: 1 kg",
    "Prawns: 500 g",
    "Soya chunks: 500 g pack",
    "Paneer: 400 g",
    "Tofu: 400 g",
    "Curd: 2 kg (hang 1 kg for hung curd)",
    "Oats: 500 g",
    "Bananas: 7, apples: 5",
    "Roasted chana: 300 g",
    "Almonds / peanuts: 200 g",
    "Vegetables for sabzi and salad",
    "Atta, dal, rajma, chole (as needed)",
  ],
  cookRules: [
    "1 teaspoon oil per person per dish",
    "No butter, cream, malai or ghee tadka on top",
    "Weigh chicken: 200 g per meal",
    "Lunch is always vegetarian (soya, paneer, tofu, dal, rajma or chole)",
    "Lunch: 2 roti. Dinner: 1 roti or half cup rice",
    "Half the plate vegetables at lunch and dinner",
  ],
  cookRulesHi: [
    "Har dish mein ek aadmi ke liye sirf 1 chammach tel",
    "Butter, cream, malai ya upar se ghee ka tadka nahi",
    "Chicken tol ke: har meal mein 200 gram",
    "Dopahar ka khana hamesha veg (soya, paneer, tofu, dal, rajma ya chole)",
    "Dopahar 2 roti. Raat ko 1 roti ya aadha cup chawal",
    "Lunch aur dinner mein aadhi plate sabzi",
  ],
};
